.TH NOTEPADQQ "1" "Oct 2019" "2.0.0-beta" "User Commands"
.SH NAME
Notepad \- Notepad++-like editor for Linux

.SH SYNOPSIS
.B notepad
.br
.B notepad
[\-h|\-\-help]
.br
.B notepad
[\-v|\-\-version]
.br
.B notepad
[\fIOPTION\fR]... [\fIFILE\fR...]

.SH DESCRIPTION
.B notepad
is a text editor for developers, with support for more than 100
programming languages, code folding, multiple selection, and much more.

.SH OPTIONS
.TP
\fB\-\-new\-window\fR
Open the files in a new window of an existing instance of
.B notepad.

.TP
\fB\-l, \-\-line <line>\fR
Opens the given file at line <line>.

.TP
\fB\-c, \-\-column <col>\fR
Opens the given file at column <col>.

.SH COPYRIGHT
Copyright \(co 2010-2018, Daniele Di Sarli <danieleds0@gmail.com>
.PP
This program is free software; you may redistribute it under
the terms of the GNU General Public License version 3 or (at
your option) any later version.  This program has absolutely
no warranty.
